version: 2.1
orbs:
  test-runner: ghostinspector/test-runner@1.0.0
jobs:
  build:
    executor: ghostinspector/default
    steps:
      - ghostinspector/execute-test:
        id: 5e2a358066fbd91d8bf6c29c
        wait: true