version: 2.1
orbs:
  orb-tools: circleci/orb-tools@volatile
  ghostinspector: ghostinspector/test-runner@1.0.0

executors:
  docker-executor:
    docker: 
      - image: docker:17.05.0-ce-git

jobs:
  execute-test-command:
    executor: ghostinspector/default
    steps:
      - ghostinspector/execute-test:
          start-url: https://staging.dorsa.ai/accounts/login/
          id: 5e522ba041e57960a8c8addc
          extra-params: '{"paramOne": "expected value 1", "paramTwo": "expected value 2"}'
          wait: true
  execute-suite-command:
    executor: ghostinspector/default
    steps:
      - ghostinspector/execute-suite:
          start-url: https://staging.dorsa.ai/accounts/login/
          id: 5e28a95ebf494e1e71341919
          extra-params: '{"paramOne": "expected value 1", "paramTwo": "expected value 2"}'
          wait: true
  test-standalone-app-command:
    executor: docker-executor
    steps:
      - setup_remote_docker
      - run:
          name: Set up temporary docker network
          command: docker network create gi-docker-network
      - run:
          name: Start your application container, specifying application port and docker network
          command: |
            docker pull ghostinspector/test-runner-standalone
            docker run \
              -e NGROK_TOKEN=1YifwszKb6W5HrvQ6RUCHfcmHvf_7R7xg2vxXScU4tCToTcQF \
              -e GI_API_KEY=$GI_API_KEY \
              -e GI_SUITE=5e28a95ebf494e1e71341919 \
              -e APP_PORT=127.0.0.1:8000 \
              --network gi-docker-network \
              --name dorsastagingtest \
              ghostinspector/test-runner-standalone
      - ghostinspector/test-standalone-app:
          #start-url: https://staging.dorsa.ai/accounts/login/
          suite-id: 5e28a95ebf494e1e71341919
          network: gi-docker-network
          extra-params: '{"sha":"563d73c2d9fe36eef732b36e3c1567b23b278fb3655cfd9b1c9759f03cd72140"}'
          vpn-token: 1YifwszKb6W5HrvQ6RUCHfcmHvf_7R7xg2vxXScU4tCToTcQF
          vpn-target: ghostinspector/test-runner-standalone:8000
workflows:
  test:
    jobs:
      #- execute-test-command
      #- execute-suite-command
      - test-standalone-app-command